src/Entity/Word.php
<?php

namespace App\Entity;

use App\Entity\Theme;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\WordRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: WordRepository::class)]
class Word
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $grammatical_class = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fr_label = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $de_label = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $en_label = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $eo_label = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $br_label = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $path_illustration = null;

    #[ORM\ManyToMany(targetEntity: Theme::class, inversedBy: 'words')]
    private Collection $themes;

    public function __construct()
    {
        $this->themes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGrammaticalClass(): ?string
    {
        return $this->grammatical_class;
    }

    public function setGrammaticalClass(?string $grammatical_class): self
    {
        $this->grammatical_class = $grammatical_class;

        return $this;
    }

    public function getFrLabel(): ?string
    {
        return $this->fr_label;
    }

    public function setFrLabel(?string $fr_label): self
    {
        $this->fr_label = $fr_label;

        return $this;
    }

    public function getDeLabel(): ?string
    {
        return $this->de_label;
    }

    public function setDeLabel(?string $de_label): self
    {
        $this->de_label = $de_label;

        return $this;
    }

    public function getEnLabel(): ?string
    {
        return $this->en_label;
    }

    public function setEnLabel(?string $en_label): self
    {
        $this->en_label = $en_label;

        return $this;
    }

    public function getEoLabel(): ?string
    {
        return $this->eo_label;
    }

    public function setEoLabel(?string $eo_label): self
    {
        $this->eo_label = $eo_label;

        return $this;
    }

    public function getBrLabel(): ?string
    {
        return $this->br_label;
    }

    public function setBrLabel(?string $br_label): self
    {
        $this->br_label = $br_label;

        return $this;
    }

    public function getPathIllustration(): ?string
    {
        return $this->path_illustration;
    }

    public function setPathIllustration(?string $path_illustration): self
    {
        $this->path_illustration = $path_illustration;

        return $this;
    }

    /**
     * @return Collection<int, Theme>
     */
    public function getThemes(): Collection
    {
        return $this->themes;
    }

    public function addTheme(Theme $theme): self
    {
        if (!$this->themes->contains($theme)) {
            $this->themes->add($theme);
        }

        return $this;
    }

    public function removeTheme(Theme $theme): self
    {
        $this->themes->removeElement($theme);

        return $this;
    }
}

src/Form/WordType.php
<?php

namespace App\Form;

use App\Entity\Word;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WordType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('fr_label')
            ->add('de_label')
            ->add('en_label')
            ->add('eo_label')
            ->add('br_label')
            ->add('path_illustration')
            ->add('grammatical_class')
            //->add('themes')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Word::class,
        ]);
    }
}

src/Controller/WordController.php
<?php

namespace App\Controller;

use App\Entity\Word;
use App\Form\WordType;
use App\Repository\WordRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/word')]
class WordController extends AbstractController
{
    #[Route('/', name: 'app_word_index', methods: ['GET'])]
    public function index(WordRepository $wordRepository): Response
    {
        return $this->render('word/index.html.twig', [
            'words' => $wordRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_word_new', methods: ['GET', 'POST'])]
    public function new(Request $request, WordRepository $wordRepository): Response
    {
        $word = new Word();
        $form = $this->createForm(WordType::class, $word);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $wordRepository->save($word, true);

            return $this->redirectToRoute('app_word_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('word/new.html.twig', [
            'word' => $word,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_word_show', methods: ['GET'])]
    public function show(Word $word): Response
    {
        return $this->render('word/show.html.twig', [
            'word' => $word,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_word_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Word $word, WordRepository $wordRepository): Response
    {
        $form = $this->createForm(WordType::class, $word);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $wordRepository->save($word, true);

            return $this->redirectToRoute('app_word_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('word/edit.html.twig', [
            'word' => $word,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_word_delete', methods: ['POST'])]
    public function delete(Request $request, Word $word, WordRepository $wordRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$word->getId(), $request->request->get('_token'))) {
            $wordRepository->remove($word, true);
        }

        return $this->redirectToRoute('app_word_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/word/_delete_form.html.twig
<form method="post" action="{{ path('app_word_delete', {'id': word.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ word.id) }}">
    <button class="btn">Delete</button>
</form>

templates/word/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/word/edit.html.twig
{% extends 'base.twig' %}

{% block title %}{{ parent() }} - Mot à modifier{% endblock %}

{% block main %}
<section class="p-2">
    <h1>Modifier un mot</h1>
    {{ include('word/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_word_index') }}">back to list</a>

    {{ include('word/_delete_form.html.twig') }}
</section>
{% endblock %}

templates/word/index.html.twig
{% extends 'base.twig' %}

{% block title %}{{ parent() }} - Mots en série{% endblock %}

{% block main %}
<section class="p-2">
    <h1>Série de mots (thème [?])</h1>

</section>
{% endblock %}

templates/word/new.html.twig
{% extends 'base.twig' %}

{% block title %}{{ parent() }} - Mot à ajouter{% endblock %}

{% block main %}
<section class="p-2">
    <h1>Ajouter un mot</h1>

    {{ include('word/_form.html.twig') }}

    <a href="{{ path('admin_words') }}">back to list</a>
</section>
{% endblock %}

templates/word/show.html.twig
{% extends 'base.twig' %}

{% block title %}{{ parent() }} - Mot en détails{% endblock %}

{% block main %}
<section class="p-2">
    <h1>Mot [id {{ word.id }}] ({{ word.grammaticalClass }})</h1>

    <div>
        <aside>
            <img src="{{ word.pathIllustration }}" alt="illustration">
        </aside>
        <div>
            <ul>
                <li><img class="icon_small" src="/img/icons/flag_fr.png" alt="français" /> {{ word.frLabel }}</li>
                <li><img class="icon_small" src="/img/icons/flag_de.png" alt="allemand" /> {{ word.deLabel }}</li>
                <li><img class="icon_small" src="/img/icons/flag_an.png" alt="anglais" /> {{ word.enLabel }}</li>
                <li><img class="icon_small" src="/img/icons/flag_eo.png" alt="espéranto" /> {{ word.eoLabel }}</li>
                <li><img class="icon_small" src="/img/icons/flag_br.png" alt="breton" /> {{ word.brLabel }}</li>
            </ul>
        </div>
    </div>

    <a href="{{ path('app_word_index') }}">back to list</a>

    <a href="{{ path('app_word_edit', {'id': word.id}) }}">edit</a>

    {{ include('word/_delete_form.html.twig') }}
</section>
{% endblock main %}