src/Entity/Theme.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ThemeRepository;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use App\Entity\User ;

#[ORM\Entity(repositoryClass: ThemeRepository::class)]
class Theme
{
    use TimestampableEntity;
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $label_fr_fr = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $label_de_de = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $path_logo = null;

    #[ORM\Column(nullable: true, options: [
        "default" => true
    ])]
    private ?bool $is_public = null;

    #[ORM\ManyToOne(inversedBy: 'themesCreated')]
    #[ORM\JoinColumn(nullable: false)]
    private ?user $created_by = null;

    #[ORM\ManyToMany(targetEntity: Word::class, mappedBy: 'themes')]
    private Collection $words;

    public function __construct()
    {
        $this->words = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabelFrFr(): ?string
    {
        return $this->label_fr_fr;
    }

    public function setLabelFrFr(?string $label_fr_fr): self
    {
        $this->label_fr_fr = $label_fr_fr;

        return $this;
    }

    public function getLabelDeDe(): ?string
    {
        return $this->label_de_de;
    }

    public function setLabelDeDe(?string $label_de_de): self
    {
        $this->label_de_de = $label_de_de;

        return $this;
    }

    public function getPathLogo(): ?string
    {
        return $this->path_logo;
    }

    public function setPathLogo(?string $path_logo): self
    {
        $this->path_logo = $path_logo;

        return $this;
    }

    public function isIsPublic(): ?bool
    {
        return $this->is_public;
    }

    public function setIsPublic(bool $is_public): self
    {
        $this->is_public = $is_public;

        return $this;
    }

    public function getCreatedBy(): ?user
    {
        return $this->created_by;
    }

    public function setCreatedBy(?user $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

    /**
     * @return Collection<int, Word>
     */
    public function getWords(): Collection
    {
        return $this->words;
    }

    public function addWord(Word $word): self
    {
        if (!$this->words->contains($word)) {
            $this->words->add($word);
            $word->addTheme($this);
        }

        return $this;
    }

    public function removeWord(Word $word): self
    {
        if ($this->words->removeElement($word)) {
            $word->removeTheme($this);
        }

        return $this;
    }
}

src/Form/ThemeType.php
<?php

namespace App\Form;

use App\Entity\Theme;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ThemeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('label_fr_fr')
            ->add('label_de_de')
            ->add('path_logo')
            ->add('is_public')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Theme::class,
        ]);
    }
}

src/Controller/ThemeController.php
<?php

namespace App\Controller;

use App\Entity\Theme;
use App\Form\ThemeType;
use App\Repository\ThemeRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/theme')]
class ThemeController extends AbstractController
{
    #[Route('/', name: 'app_theme_index', methods: ['GET'])]
    public function index(ThemeRepository $themeRepository): Response
    {
        return $this->render('theme/index.html.twig', [
            'themes' => $themeRepository->findAll(),
        ]);
    }

    /**
     * Create a new Theme
     * RESTRICTED TO admins
     */
    #[Route('/new', name: 'app_theme_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function new(Request $request, ThemeRepository $themeRepository): Response
    {
        $theme = new Theme();
        $form = $this->createForm(ThemeType::class, $theme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $theme->setCreatedBy($this->getUser());
            $themeRepository->save($theme, true);

            return $this->redirectToRoute('app_theme_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('theme/new.html.twig', [
            'theme' => $theme,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_theme_show', methods: ['GET'])]
    public function show(Theme $theme): Response
    {
        return $this->render('theme/show.html.twig', [
            'theme' => $theme,
        ]);
    }

    /**
     * Update an existing Theme
     * RESTRICTED TO admins
     */
    #[Route('/{id}/edit', name: 'app_theme_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function edit(Request $request, Theme $theme, ThemeRepository $themeRepository): Response
    {
        $form = $this->createForm(ThemeType::class, $theme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $themeRepository->save($theme, true);

            return $this->redirectToRoute('app_theme_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('theme/edit.html.twig', [
            'theme' => $theme,
            'form' => $form,
        ]);
    }

    /**
     * Delete a Theme
     * RESTRICTED TO admins
     */
    #[Route('/{id}', name: 'app_theme_delete', methods: ['POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function delete(Request $request, Theme $theme, ThemeRepository $themeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$theme->getId(), $request->request->get('_token'))) {
            $themeRepository->remove($theme, true);
        }

        return $this->redirectToRoute('app_theme_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/theme/_delete_form.html.twig
<form method="post" action="{{ path('app_theme_delete', {'id': theme.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ theme.id) }}">
    <button class="btn">Delete</button>
</form>

templates/theme/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/theme/edit.html.twig
{% extends 'base.twig' %}

{% block title %}{{ parent() }} - Thèmes{% endblock %}

{% block main %}
<section class="p-2">
    <h1>Modifier un thème</h1>

    {{ include('theme/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_theme_index') }}">back to list</a>

    {{ include('theme/_delete_form.html.twig') }}
</section>
{% endblock main %}

templates/theme/index.html.twig
{% extends 'base.twig' %}

{% block title %}{{ parent() }} - Thèmes{% endblock %}

{% block main %}
<section class="p-2">
    <h1>Liste du vocabulaire par thèmes</h1>

    <ul class="cards">
        {% for theme in themes %}
        <li class="cards_item">
          <div class="card">
            <div class="card_image">
                <img class="vignette" src="{{ theme.pathLogo }}" alt="" />
            </div>
            <div class="card_content">
              <h2 class="card_title"><img class="icon_micro" src="/img/icons/flag_fr.png" alt="français" />
                {{ theme.labelFrFr }}</h2>
              <p class="card_text"><img class="icon_micro" src="/img/icons/flag_de.png" alt="allemand" />
                {{ theme.labelDeDe }}</p>
              <button class="btn card_btn" disabled>Réviser cette série</button>
              {#<a href="{{ path('app_theme_show', {'id': theme.id}) }}">#}
            </div>
          </div>
        </li>
        {% else %}
        <li>Aucun thème n'est actuellement disponible.</li>
        {% endfor %}
        </ul>

</section>
{% endblock main %}

templates/theme/new.html.twig
{% extends 'base.twig' %}

{% block title %}{{ parent() }} - Thème{% endblock %}

{% block main %}<section class="p-2">

    <h1>Créer un nouveau Thème</h1>

    {{ include('theme/_form.html.twig') }}

    <a href="{{ path('admin_themes') }}">back to list</a>
</section>
{% endblock %}

templates/theme/show.html.twig
{% extends 'base.twig' %}

{% block title %}{{ parent() }} - Thème{% endblock %}

{% block main %}<section class="p-2">
    <h1>Thème "{{ theme.labelFrFr }}" (id {{ theme.id }})</h1>
    <p>Créat·eur·rice : {{ theme.createdBy.username }}</p>

    <p>Thème {{ theme.isPublic ? 'Public' : 'Privé' }}</p>
    <p>Illustration :</p>
    <img src="{{ theme.pathLogo }}" alt="illustration de {{ theme.labelFrFr }}">


    <h2>Traduction</h2>
    <ul>
        <li><img class="icon_small" src="/img/icons/flag_fr.png" alt="français" /> {{ theme.labelFrFr }}</li>
        <li><img class="icon_small" src="/img/icons/flag_de.png" alt="allemand" /> {{ theme.labelDeDe }}</li>
        <li><img class="icon_small" src="/img/icons/flag_an.png" alt="anglais" /> {# theme.label #}</li>
        <li><img class="icon_small" src="/img/icons/flag_eo.png" alt="espéranto" /> {# theme.label #}</li>
        <li><img class="icon_small" src="/img/icons/flag_br.png" alt="breton" /> {# theme.label #}</li>
    </ul>

    <p>Création le {{ theme.createdAt ? theme.createdAt|date('Y-m-d H:i:s') : '' }}</p>
    <p>Dernière édition le {{ theme.updatedAt ? theme.updatedAt|date('Y-m-d H:i:s') : '' }}</p>

    <a href="{{ path('app_theme_index') }}">back to list</a>

    <a href="{{ path('app_theme_edit', {'id': theme.id}) }}">edit</a>

    {{ include('theme/_delete_form.html.twig') }}
    
</section>
{% endblock main %}